### ISSUE TITLE
New metadata structure & provider/country data

### ISSUE THREAD

**Issue by riordan** [openaq/openaq-open-data#7]
I noticed that in:
- #2 

there was a migration from multi-hierarchy hive partitioning  `[country | provider | locationid] / year / month`  to a more traditional single hierarchy hive partition under `locationid / year / month`. Having done that is great, as it certainly speeds up reads to have a single hierarchy, not just writes. (Also I think it's more canonical to the standard to the extent that there actually is one, which there might not be).

This brings up 2 things:

1. `ahem this is more of a statement than a question`: It would appear that the existing providers & hierarchies partitions are no longer being updated. It would be great to see that deprecation noted in the Direct File Access docs for [S3](https://docs.openaq.org/docs/accessing-openaq-archive-data) and [Querying Athena](https://docs.openaq.org/docs/querying-with-aws-athena)
2. Does this mean that records written to S3 no longer have country or provider data being written, as that data was being recorded in the partition-created column, rather than being recorded into the .csv.gz record?

**Comment by russbiggs** [comment]
Thanks for raising this. yes the country/provider were deprecated in November 2023. Deprecation was announced via our Slack (the best place to get up-to-date info). It does look like there was an oversight to update the docs, specifically the Athena page. 

Country and provider proved to be less stable than expected and removing them from the partitioning scheme does make scanning large volumes much easy. Country and provider data is not written to the file, but is available via the API, like any other location metadata.
